
services:
  seaweb:
    image:nginx
    container_name: webcone
    ports:
      - 80:80
    volumes:
      - $(pwd):/etc/nginx/website/
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
